version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    groups:
      kube-ecosystem:
        patterns: ["kube", "k8s-openapi", "schemars"]
      tracing:
        patterns: ["tracing*"]
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: weekly
