//! A generated artifact (relative path under `deploy/` + its YAML content) and
//! the write / `--check` drift logic shared by every subcommand.

use std::path::Path;

use anyhow::{Context, Result};

use crate::paths::deploy_dir;

/// Header prepended to every generated file. Kept as a single source of truth
/// so the write path and the bundle-stripping path agree byte-for-byte.
pub const GEN_HEADER: &str = "# GENERATED by `cargo xtask gen-crds` — DO NOT EDIT\n";

/// Header used for RBAC files (different subcommand name in the hint).
pub const RBAC_HEADER: &str = "# GENERATED by `cargo xtask gen-rbac` — DO NOT EDIT\n";

/// A single generated file: a path relative to `deploy/` and its full content.
#[derive(Debug, Clone)]
pub struct Artifact {
    /// Path relative to the `deploy/` directory, e.g. `crds/repositories.yaml`.
    pub rel_path: String,
    /// Full file content including the generated-file header.
    pub content: String,
}

impl Artifact {
    pub fn new(rel_path: String, content: String) -> Self {
        Self { rel_path, content }
    }
}

/// Write all artifacts to disk under `deploy/`, creating parent dirs as needed.
pub fn write_all(artifacts: &[Artifact]) -> Result<()> {
    let root = deploy_dir();
    for a in artifacts {
        let path = root.join(&a.rel_path);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("creating directory {}", parent.display()))?;
        }
        std::fs::write(&path, &a.content).with_context(|| format!("writing {}", path.display()))?;
        println!("wrote {}", path.display());
    }
    Ok(())
}

/// Compare all artifacts against the checked-in files without writing anything.
///
/// Returns `Ok(true)` if everything matches (no drift), `Ok(false)` if any file
/// is missing or differs (drift detected; a human-readable message is printed
/// to stderr for each mismatch).
pub fn check_all(artifacts: &[Artifact]) -> Result<bool> {
    let root = deploy_dir();
    let mut ok = true;
    for a in artifacts {
        let path = root.join(&a.rel_path);
        match std::fs::read_to_string(&path) {
            Ok(on_disk) if on_disk == a.content => {}
            Ok(on_disk) => {
                ok = false;
                eprintln!("DRIFT: {} differs from generated output", path.display());
                report_first_diff(&on_disk, &a.content);
            }
            Err(_) => {
                ok = false;
                eprintln!(
                    "DRIFT: {} is missing (run `cargo xtask gen-all`)",
                    path.display()
                );
            }
        }
    }
    Ok(ok)
}

/// Print the first differing line to give reviewers a quick pointer.
fn report_first_diff(on_disk: &str, generated: &str) {
    for (i, (a, b)) in on_disk.lines().zip(generated.lines()).enumerate() {
        if a != b {
            eprintln!("  first diff at line {}:", i + 1);
            eprintln!("    on-disk:   {a}");
            eprintln!("    generated: {b}");
            return;
        }
    }
    // No line differed within the common prefix => length differs.
    eprintln!(
        "  content length differs (on-disk {} bytes, generated {} bytes)",
        on_disk.len(),
        generated.len()
    );
}

/// Convenience: does this relative path exist under `deploy/`?
pub fn exists(rel_path: &str) -> bool {
    Path::new(&deploy_dir().join(rel_path)).exists()
}
