//! CRD YAML generation.
//!
//! For each of the 8 `kopiur.home-operations.com` CRDs we call `T::crd()` (the `CustomResourceExt`
//! method generated by the `kube::CustomResource` derive), serialize the
//! resulting `CustomResourceDefinition` to YAML, prepend a generated-file
//! header, and emit it at `deploy/crds/<plural>.yaml`. A concatenated
//! `deploy/crds/all-crds.yaml` is also produced for one-shot `kubectl apply`.
//!
//! The same per-CRD content is ALSO emitted to the Helm chart's
//! `deploy/helm/kopiur/files/crds/<plural>.yaml`, so the chart's CRD copies are a
//! generated artifact under the `gen-all --check` drift guard rather than a
//! hand-maintained copy that can silently go stale.

use anyhow::{Context, Result};
use kube::core::CustomResourceExt;

use crate::artifact::{Artifact, GEN_HEADER};

/// Serialize a single CRD type to YAML with the generated header prepended.
fn render_crd<T: CustomResourceExt>() -> Result<(String, String)> {
    let crd = T::crd();
    let plural = crd.spec.names.plural.clone();
    let body = serde_yaml::to_string(&crd)
        .with_context(|| format!("serializing CRD '{plural}' to YAML"))?;
    let content = format!("{GEN_HEADER}{body}");
    Ok((plural, content))
}

/// Generate all CRD artifacts (8 per-CRD files plus the concatenated bundle).
pub fn artifacts() -> Result<Vec<Artifact>> {
    // (plural, content) for each CRD, generated in a stable order.
    let crds: Vec<(String, String)> = vec![
        render_crd::<kopiur_api::Repository>()?,
        render_crd::<kopiur_api::ClusterRepository>()?,
        render_crd::<kopiur_api::SnapshotPolicy>()?,
        render_crd::<kopiur_api::Snapshot>()?,
        render_crd::<kopiur_api::SnapshotSchedule>()?,
        render_crd::<kopiur_api::Restore>()?,
        render_crd::<kopiur_api::Maintenance>()?,
        render_crd::<kopiur_api::RepositoryReplication>()?,
    ];

    let mut out = Vec::with_capacity(crds.len() + 1);
    let mut bundle_parts: Vec<String> = Vec::with_capacity(crds.len());

    for (plural, content) in &crds {
        out.push(Artifact::new(
            format!("crds/{plural}.yaml"),
            content.clone(),
        ));
        // The Helm chart ships its own copy under `files/crds/` (loaded via
        // `.Files.Glob`); emit it from the same source so it can never silently
        // drift from `deploy/crds/`, and so the `gen-all --check` guard covers it
        // too. Otherwise a CRD field change would ship a stale chart CRD whose
        // structural schema prunes the new field on every `helm install`.
        out.push(Artifact::new(
            format!("helm/kopiur/files/crds/{plural}.yaml"),
            content.clone(),
        ));
        // For the bundle, strip each file's leading header so we get one header
        // up top and clean `---`-joined documents.
        let body = content.strip_prefix(GEN_HEADER).unwrap_or(content);
        bundle_parts.push(body.trim_end().to_string());
    }

    let bundle = format!("{GEN_HEADER}{}\n", bundle_parts.join("\n---\n"));
    out.push(Artifact::new("crds/all-crds.yaml".to_string(), bundle));

    Ok(out)
}
