//! Drift guard test: after `cargo xtask gen-all` has written the checked-in
//! files, the in-process `--check` logic must report no drift. This mirrors what
//! CI runs (`cargo xtask gen-all --check`) but inside the test harness.
//!
//! Note: this test depends on `deploy/` being up to date on disk. The committed
//! artifacts are generated by `cargo xtask gen-all`; if you change a CRD or RBAC
//! rule, regenerate before running.

use xtask::artifact::check_all;

#[test]
fn generated_artifacts_match_checked_in_files() {
    let artifacts = xtask::collect("gen-all").expect("collect gen-all artifacts");
    let no_drift = check_all(&artifacts).expect("run drift check");
    assert!(
        no_drift,
        "checked-in deploy/ artifacts are stale; run `cargo xtask gen-all` and commit"
    );
}
